/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ride.sharing;

import org.junit.jupiter.api.Test;


public class GeektrustTest {

    @Test
    public void app() {}
}
